// A game demo used as a submission__Author Yan Wei.

#pragma once

#include "NativeGameplayTags.h"


namespace IllusionGameplayTags
{
	/** Input Tags **/
	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Zoom);
	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipWeapon_Sword);
	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnquipWeapon_Sword);
	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Sword);
	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Sword);


	/** Player Tags **/
	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Sword);
	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Sword);
	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Sword);
	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Sword);
	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Ranged_SwordEnergy); //½£Æø


	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Sword);

	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Sword);
	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Sword);



	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);

	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);

	/** Enemy Tags **/
	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);

	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);


	/** Shared Tags **/
	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_RemoteHit);//Ô¶³Ì
	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_Spawn_Projectile);//Ô¶³Ì
	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_Spawn_SwordEnergy);
	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);


	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);

	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);


	DEMOILLUSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead);


}
